### ISSUE TITLE
bl2bids could/should update subject name in sidecar?

### ISSUE THREAD

**Issue by soichih** [brainlife/abcd-spec#29]
I see this error message on app-fmriprep

```
bids.exceptions.BIDSConflictingValuesError: Conflicting values found for entity 'subject' in filename /export/prod/5fceafe6d89d016a3e5d429a/60b9e984979fdc1caa86a064/bids/sub-sub21/anat/sub-sub21_T1w.nii.gz (value='sub21') versus its JSON sidecar (value='sub-21'). Please reconcile this discrepancy.
```

Indeed, the son sidecar contains value "sub-21" but BIDS path uses "sub21".

![image](https://user-images.githubusercontent.com/923896/120807673-32f80700-c516-11eb-8af2-afeeb3ca877c.png)

I believe bl2bids is dropping the "-" inside the subject name for the bids path (as required by BIDS spec), but it's not updating the sidecar with modified subject name. 

@giulia-berto Can you take a look?

**Comment by giulia-berto** [comment]
sure, I sent you a PR https://github.com/brainlife/abcd-spec/pull/28
