### ISSUE TITLE
PermissionError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/abcd-spec#3]
I got this with the new function copyJSON (running on Jetstream/slurm7 @ TACC):
```
Traceback (most recent call last):
  File "/home/user/abcd-spec/hooks/slurm/bl2bids", line 319, in <module>
    copyJSON(src, dest+"_phase1.json", override={"IntendedFor": intended_paths})
  File "/home/user/abcd-spec/hooks/slurm/bl2bids", line 57, in copyJSON
    with open(dest, 'w') as outfile:
PermissionError: [Errno 13] Permission denied: 'bids/sub-9002/ses-1/fmap/sub-9002_ses-1_phase1.json'
```

**Comment by soichih** [comment]
I am guessing you are rerunning a job? Can you try submitting a new job? I believe the phase1.json is still using a symlink setup by previous run and like I mentioned, you won't be able to modify the input data as they are stored as read-only.

**Comment by giulia-berto** [comment]
no it was actually a new job, both with master and 20.2.1 branches

**Comment by soichih** [comment]
I've fixed this issue > https://github.com/brainlife/abcd-spec/commit/5c36d924cc875e0cbd85ec0b1fd77c3985cd37df
