### ISSUE TITLE
Q: why smon is "attaching" to session id instead of being used as a "wrapper" around an app?

### ISSUE THREAD

**Issue by yarikoptic** [brainlife/abcd-spec#35]
@soichih pointed us to https://github.com/brainlife/abcd-spec/blob/master/hooks/smon which is a great, and we would like to work off it for a very similar but brainlife-independent and a little parametrizable and hopefully a bit easier to use tool which we will call https://github.com/con/duct .

While reviewing it I wondered why you decided to make `smon` to attach/monitor existing session id, instead of just making it  a "wrapper" script around execution of a command -- this way you could avoid duplicating all the invocation/killing logic you have across wrappers like https://github.com/brainlife/abcd-spec/blob/HEAD/hooks/direct/start#L25 ?

May be there is another reason/use-case where you use `smon` besides those hooks?

**Comment by soichih** [comment]
Ah so basically let smon do the start up of `main` (or maybe whichever command that's given) and wait for it to exit while running a loop for "ps" command? I think that should work! I don't know why I set it up like it is, but my guess is that I didn't want smon to affect the execution of the main.. Like if smon crashes, I didn't want the main script to be terminated.. maybe?

**Comment by yarikoptic** [comment]
> and wait for it to exit while running a loop for "ps" command?

yes

> Like if smon crashes, I didn't want the main script to be terminated.. maybe?

makes sense... Thank you @soichih !
