### ISSUE TITLE
Q: smon - was collecting stats per process "warranted"?

### ISSUE THREAD

**Issue by yarikoptic** [brainlife/abcd-spec#36]
smon collects stats per process, while aggregating (max) across 30 samples sampled each 2 seconds.

- we wondered if you had good use cases for collecting such detailed (per process) instead of crude aggregate (across all processes) for analysis later on.

- how do you estimate total memory utilization across processes then: seems might be a little bit "on the overestimation side" if those processes manage to go up/down within that minute -- would be a sum of peaks?

**Comment by soichih** [comment]
When an app suddenly starts consuming a lot of memory and OOMs, we needed a shorter time frame (like 2 seconds) to capture that event (to know which process is causing the OOM), but it was overkill to store information at 2 seconds granularity. So smon collects the *maximum* resource usage within 30*2 seconds window.  smon doesn't *sum* resource usage.. I just look at the *max*, I think.

**Comment by soichih** [comment]
Ah I think I get your question now.

Yes, the output from smon can be summed up to show the total resource utilization - which could be overestimated. In reality though, I don't think it was ever an issue.

**Comment by yarikoptic** [comment]
rright, and then you can pin point specific process which caused large memory consumption... indeed could be handy.

Thanks!
