### ISSUE TITLE
No module named 'nibabel'

### ISSUE THREAD

**Issue by giulia-berto** [brainlife/abcd-spec#5]
In the new version of bl2bids, nibabel is needed to read the affine from the .nii images. Where should we install it? Can we use a docker container to run bl2bids?

**Comment by soichih** [comment]
Yes, we need to run it via singularity now that we are using nibabel.

I just renamed bl2bids to bl2bids.py and made bl2bids a shell script that execute bl2bids.py with singularity.

**Comment by giulia-berto** [comment]
great thanks! I got this error however: `FATAL:  stat /geode2/home/u010/brlife/Carbonate/abcd-spec/hooks/bl2bids.py: no such file or directory`

**Comment by soichih** [comment]
it should be on the latest master.
> https://github.com/brainlife/abcd-spec/blob/master/hooks/bl2bids.py
did you do git pull?

**Comment by giulia-berto** [comment]
sorry, it was running the fmriprep app: https://brainlife.io/project/5a78c177340591004da75e6f/process/5fecbf75f2246d34238b99fd#5ff7477d0df8ff74bf3eee2e

**Comment by soichih** [comment]
I believe I've fixed this. Can you try again?

**Comment by giulia-berto** [comment]
I still have it, but only if it runs on my personal carbonate account
```INFO:    Using cached SIF image
FATAL:   stat /geode2/home/u010/brlife/Carbonate/abcd-spec/hooks/bl2bids.py: no such file or directory
Signal 15 (TERM) caught by ps (procps-ng version 3.3.10).
ps:display.c:66: please report this bug
```

**Comment by giulia-berto** [comment]
Working now, thanks!
